name: "Helllo Actions"
description: "Greet someone"
author: "bradley.stannard@db.com"


inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: docker
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"